apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb
    isDefault: true
    jsonData:
      version: Flux
      organization: home
      defaultBucket: inverter
      tlsSkipVerify: true
      httpTimeout: 60
      minInterval: "30s"
    secureJsonData:
      token: $INFLUX_TOKEN

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      maxLines: 1000
